version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: usermanagement-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:7
    container_name: usermanagement-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: usermanagement_profiles
    volumes:
      - mongodb_data:/data/db

volumes:
  redis_data:
  mongodb_data:
