version: '3.8'

services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: usermanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"      // for node to node communications
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - elasticsearch

# Volumes for data persistence
volumes:
  postgres_data:
  elasticsearch_data:
