version: '3.8'

services:
  # PostgresSQL Database
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: usermanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Spring Boot Application
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

# Volumes for data persistence
volumes:
  postgres_data:
